---

- name: invoke the role for /etc/iaac for hosts group iaas
  hosts: iaas
  become: yes

  roles:
      - create_empty_file

- name: invoke the role for defining variable for all hosts
  hosts: all
  become: yes

  roles:
      - define_content

  tasks:
      - name: print in registered variables along with hostnames
        debug:
            msg: "{{ content.stdout }} from {{ ansible_hostname }}"


